let mix = require('laravel-mix');
let del = require('del');
/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for your application, as well as bundling up your JS files.
 |
 */
mix
    //后台主题
    .less('public/backend/src/less/main.less', 'public/backend/dist/css', {
        lessOptions: {
            paths: [path.resolve(__dirname, 'node_modules')],
        },
    }).options({
        processCssUrls: false
    })
    .js('public/backend/src/js/main.js', 'public/backend/dist/js')
    // //前端主题 basic
    // .less('themes/basic/assets/src/less/theme.less', 'themes/basic/assets/dist/css')
    //前端主题 clothes
    // .webpackConfig({
    //     module: {
    //         rules: [
    //             {
    //                 test: /\.(png|jpg|gif)$/,
    //                 loaders: [{
    //                     loader: 'url-loader',
    //                     options: {
    //                         mimetype: 'image/png'
    //                     }
    //                 }]
    //             }
    //         ]
    //     }

    // })
    .less('themes/clothes/assets/src/less/clothes.less', 'themes/clothes/assets/dist/css')
    .js('themes/clothes/assets/src/js/clothes.js', 'themes/clothes/assets/dist/js')
    .copy('themes/clothes/assets/src/images','themes/clothes/assets/dist/images')
    .then(function () {
        del(['public/assets/*']);
    });
//mix.js('src/app.js', 'dist/').sass('src/app.scss', 'dist/');

// Full API
// mix.js(src, output);
// mix.react(src, output); <-- Identical to mix.js(), but registers React Babel compilation.
// mix.preact(src, output); <-- Identical to mix.js(), but registers Preact compilation.
// mix.coffee(src, output); <-- Identical to mix.js(), but registers CoffeeScript compilation.
// mix.ts(src, output); <-- TypeScript support. Requires tsconfig.json to exist in the same folder as webpack.mix.js
// mix.extract(vendorLibs);
// mix.sass(src, output);
// mix.less(src, output);
// mix.stylus(src, output);
// mix.postCss(src, output, [require('postcss-some-plugin')()]);
// mix.browserSync('my-site.test');
// mix.combine(files, destination);
// mix.babel(files, destination); <-- Identical to mix.combine(), but also includes Babel compilation.
// mix.copy(from, to);
// mix.copyDirectory(fromDir, toDir);
// mix.minify(file);
// mix.sourceMaps(); // Enable sourcemaps
// mix.version(); // Enable versioning.
// mix.disableNotifications();
// mix.setPublicPath('path/to/public');
// mix.setResourceRoot('prefix/for/resource/locators');
// mix.autoload({}); <-- Will be passed to Webpack's ProvidePlugin.
// mix.webpackConfig({}); <-- Override webpack.config.js, without editing the file directly.
// mix.babelConfig({}); <-- Merge extra Babel configuration (plugins, etc.) with Mix's default.
// mix.then(function () {}) <-- Will be triggered each time Webpack finishes building.
// mix.override(function (webpackConfig) {}) <-- Will be triggered once the webpack config object has been fully generated by Mix.
// mix.dump(); <-- Dump the generated webpack config object to the console.
// mix.extend(name, handler) <-- Extend Mix's API with your own components.
// mix.options({
//   extractVueStyles: false, // Extract .vue component styling to file, rather than inline.
//   globalVueStyles: file, // Variables file to be imported in every component.
//   processCssUrls: true, // Process/optimize relative stylesheet url()'s. Set to false, if you don't want them touched.
//   purifyCss: false, // Remove unused CSS selectors.
//   terser: {}, // Terser-specific options. https://github.com/webpack-contrib/terser-webpack-plugin#options
//   postCss: [] // Post-CSS options: https://github.com/postcss/postcss/blob/master/docs/plugins.md
// });
