#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
define('RUNTIME_MODE', 'Console');
require __DIR__ . '/env.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/Config/console.php', 
    require __DIR__ . '/DuAdmin/config.php');
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);