<?php


namespace Addons\Cms\Controllers\Backend;

use Addons\Cms\Models\Page;

/**
 * 在线编辑控制器
 * Class LiveEditorController
 * @package Addons\Cms\Controllers\Backend
 */
class LiveEditorController extends \DuAdmin\Core\BackendController
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->layout = false;
    }

    public function actionIndex( $pageId )
    {
        $content = <<<HTML
<block data-block="Addons\Cms\PageBlock\Column">
</block>
HTML;

        return $this->render( 'index', ['content' => $content ] );
    }

    protected function parse($content) {

    }
}