<?php

namespace app\kit\mysql;

use yii\db\ActiveQuery as BaseActiveQuery;

class ActiveQuery extends BaseActiveQuery
{
    public $forUpdate = false;

    public function forUpdate()
    {
        $this->forUpdate = true;
        return $this;
    }


    public function createCommand($db = null)
    {
        return parent::createCommand($db); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function prepare($builder)
    {
        $query = Query::create(parent::prepare($builder), $this->forUpdate);
        return $query;
    }
}
